# Programming and Data Analysis

> Assignment 5

Kuo, Yao-Jen <yaojenkuo@ntu.edu.tw> from [DATAINPOINT](https://www.datainpoint.com)

In [ ]:
import json
import numpy as np
import pandas as pd

## Instructions

- The assignment will be disconnected if idling over 10 minutes, we can reactivate a new session by clicking the assignment link again.
- We've imported necessary modules at the top of each assignment.
- We've put necessary files(if any) in the working directory.
- We've defined the names of functions/inputs/parameters for you.
- Write down your solution between the comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- It is NECESSARY to `return` the answer, tests will fail by just printing out the answer.
- It is known that errors like `SyntaxError` or `IndentationError` breaks our `test_runner.py` and results in a zero point grade. It is highly recommended testing your solution by calling functions/methods in notebook or running tests before submission.
- Running tests to see if your solutions are right:
    - File -> Save Notebook to save `exercises.ipynb`.
    - File -> New -> Terminal to open a Terminal.
    - Use command `python test_runner.py` to run test.
- When you are ready to submit, click File -> Export Notebook As -> Executable Script.
- Rename the exported Python script with your student ID(e.g. `b01234567.py`) and upload to the Assignment session on NTU COOL/NTNU Moodle.

## 01. Define a function `create_nba_teams()` that is able to create a DataFrame of NBA franchise teams in standard league as expected given `teams.json` in working directory.

- Expected inputs: None
- Expected outputs: `pd.DataFrame`

```
        teamId tricode confName    divName           city  \
0   1610612737     ATL     East  Southeast        Atlanta   
1   1610612738     BOS     East   Atlantic         Boston   
2   1610612751     BKN     East   Atlantic       Brooklyn   
3   1610612766     CHA     East  Southeast      Charlotte   
4   1610612741     CHI     East    Central        Chicago   
5   1610612739     CLE     East    Central      Cleveland   
6   1610612742     DAL     West  Southwest         Dallas   
7   1610612743     DEN     West  Northwest         Denver   
8   1610612765     DET     East    Central        Detroit   
9   1610612744     GSW     West    Pacific   Golden State   
10  1610612745     HOU     West  Southwest        Houston   
11  1610612754     IND     East    Central        Indiana   
12  1610612746     LAC     West    Pacific             LA   
13  1610612747     LAL     West    Pacific    Los Angeles   
14  1610612763     MEM     West  Southwest        Memphis   
15  1610612748     MIA     East  Southeast          Miami   
16  1610612749     MIL     East    Central      Milwaukee   
17  1610612750     MIN     West  Northwest      Minnesota   
18  1610612740     NOP     West  Southwest    New Orleans   
19  1610612752     NYK     East   Atlantic       New York   
20  1610612760     OKC     West  Northwest  Oklahoma City   
21  1610612753     ORL     East  Southeast        Orlando   
22  1610612755     PHI     East   Atlantic   Philadelphia   
23  1610612756     PHX     West    Pacific        Phoenix   
24  1610612757     POR     West  Northwest       Portland   
25  1610612758     SAC     West    Pacific     Sacramento   
26  1610612759     SAS     West  Southwest    San Antonio   
27  1610612761     TOR     East   Atlantic        Toronto   
28  1610612762     UTA     West  Northwest           Utah   
29  1610612764     WAS     East  Southeast     Washington   

                  fullName  
0            Atlanta Hawks  
1           Boston Celtics  
2            Brooklyn Nets  
3        Charlotte Hornets  
4            Chicago Bulls  
5      Cleveland Cavaliers  
6         Dallas Mavericks  
7           Denver Nuggets  
8          Detroit Pistons  
9    Golden State Warriors  
10         Houston Rockets  
11          Indiana Pacers  
12             LA Clippers  
13      Los Angeles Lakers  
14       Memphis Grizzlies  
15              Miami Heat  
16         Milwaukee Bucks  
17  Minnesota Timberwolves  
18    New Orleans Pelicans  
19         New York Knicks  
20   Oklahoma City Thunder  
21           Orlando Magic  
22      Philadelphia 76ers  
23            Phoenix Suns  
24  Portland Trail Blazers  
25        Sacramento Kings  
26       San Antonio Spurs  
27         Toronto Raptors  
28               Utah Jazz  
29      Washington Wizards
```

In [ ]:
def create_nba_teams() -> pd.DataFrame:
    """
    >>> nba_teams = create_nba_teams()
    >>> type(nba_teams)
    pandas.core.frame.DataFrame
    >>> nba_teams.shape
    (30, 6)
    """
    ### BEGIN SOLUTION
    
    def collapse_lists(data):
        result = []
        for d in data:
            entry = {}
            if d['isNBAFranchise'] == True:
                for k, v in d.items():
                    entry.update({k: v})
                result.append(entry)
        return result

    with open('teams.json', 'r') as f:
        data = pd.DataFrame(collapse_lists(json.load(f)['league']['vegas']))

    wants = ['teamId', 'tricode', 'confName', 'divName', 'city', 'fullName']
    return(data[wants])
    
    ### END SOLUTION

## 02. Define a function `create_nba_coaches()` that is able to create a DataFrame of NBA franchise team's coaches in standard league as expected given `coaches.json` in working directory.

- Expected inputs: None.
- Expected outputs: `pd.DataFrame`

```
         tricode     coach_name  is_assistant
0            PHI     Doc Rivers         False
1            PHI  David Joerger          True
2            PHI      Dan Burke          True
3            PHI    Sam Cassell          True
4            PHI    Jamie Young          True
..           ...            ...           ...
238          WAS     Pat Delany          True
239          WAS   Joseph Blair          True
240          WAS    Mike Miller          True
241          WAS   Zach Guthrie          True
242          WAS    Dean Oliver          True

[243 rows x 3 columns]
```

In [ ]:
def create_nba_coaches() -> pd.DataFrame:
    """
    >>> nba_coaches = create_nba_coaches()
    >>> type(nba_coaches)
    pandas.core.frame.DataFrame
    >>> nba_coaches.shape
    (243, 3)
    """
    ### BEGIN SOLUTION
    
    with open('coaches.json', 'r') as f:
        data = json.load(f)["league"]["standard"]

    tri = []
    for i in data:
        tri.append(i["teamSitesOnly"]["teamTricode"])

    data = pd.DataFrame(data)
    data['tricode'] = pd.DataFrame(tri)   
    data["coach_name"] = data["firstName"] + ' ' + data["lastName"]
    data['is_assistant'] = data['isAssistant']
    
    wants = ['tricode', 'coach_name', 'is_assistant']
    return(data[wants])
    
    ### END SOLUTION

## 03. Define a function `create_nba_players()` that is able to create a DataFrame of NBA franchise team's players in standard league as expected given `players.json` in working directory.

- Expected inputs: None.
- Expected outputs: `pd.DataFrame`

```
    current_team_id        player_name
0        1610612761   Precious Achiuwa
1        1610612763       Steven Adams
2        1610612748        Bam Adebayo
3        1610612763       Santi Aldama
4        1610612751  LaMarcus Aldridge
..              ...                ...
501      1610612759     Thaddeus Young
502      1610612737         Trae Young
503      1610612748     Omer Yurtseven
504      1610612757        Cody Zeller
505      1610612746        Ivica Zubac

[506 rows x 2 columns]
```

In [ ]:
def create_nba_players() -> pd.DataFrame:
    """
    >>> nba_players = create_nba_players()
    >>> type(nba_players)
    pandas.core.frame.DataFrame
    >>> nba_players.shape
    (506, 2)
    """
    ### BEGIN SOLUTION
    
    with open('teams.json', 'r') as file:
        teams = json.load(file)
    file.close()

    standards_teams = []
    for i in teams['league']['vegas']:
        if i["isNBAFranchise"] == True:
            standards_teams.append(i['teamId'])

    def collapse_lists(data):
            result = []
            for d in data:
                entry = {}                      
                if d['teamId'] in standards_teams:
                    for k, v in d.items():
                        entry.update({k: v})
                    result.append(entry)
            return result

    with open('players.json', 'r') as f:
        data = pd.DataFrame(collapse_lists(json.load(f)['league']['standard']))

    data['current_team_id'] = data['teamId']
    data["player_name"] = data["firstName"] + ' ' + data["lastName"]
    wants = ['current_team_id', "player_name"]
    return(data[wants])

    ### END SOLUTION

## 04. Define a function `create_nba_teams_and_coaches()` which generates a current coach roster dataframe for NBA franchise teams in standard league as expected given `teams.json` and `coaches.json` in working directory.

- Expected inputs: None
- Expected outputs: `pd.DataFrame`

```
               fullName        coach_name  is_assistant
0         Atlanta Hawks     Nate McMillan         False
1         Atlanta Hawks        Chris Jent          True
2         Atlanta Hawks        Joe Prunty          True
3         Atlanta Hawks  Jamelle McMillan          True
4         Atlanta Hawks         Matt Hill          True
..                  ...               ...           ...
238  Washington Wizards        Pat Delany          True
239  Washington Wizards      Joseph Blair          True
240  Washington Wizards       Mike Miller          True
241  Washington Wizards      Zach Guthrie          True
242  Washington Wizards       Dean Oliver          True

[243 rows x 3 columns]
```

In [ ]:
def create_nba_teams_and_coaches() -> pd.DataFrame:
    """
    >>> nba_teams_and_coaches = create_nba_teams_and_coaches()
    >>> type(nba_teams_and_coaches)
    pandas.core.frame.DataFrame
    >>> nba_teams_and_coaches.shape
    (243, 3)
    """
    ### BEGIN SOLUTION
    
    with open('coaches.json', 'r') as f:
        data = json.load(f)["league"]["standard"]

    with open('coaches.json', 'r') as ff:
        coaches = json.load(ff)


    with open('teams.json', 'r') as file:
        teams = json.load(file)
    file.close()

    standard_teams = {}
    for i in teams['league']['vegas']:
        if i["isNBAFranchise"] == True:
            standard_teams.update({i["tricode"]: i["fullName"]})

    std_teams_list = []
    for i in coaches["league"]["standard"]:
        std_teams_list.append(i["teamSitesOnly"]["teamTricode"])

    data = pd.DataFrame(data)
    std_teams = []
    for i in std_teams_list:
        std_teams.append(standard_teams[i])
    data['fullName'] = pd.DataFrame(std_teams)
    data["coach_name"] = data["firstName"] + ' ' + data["lastName"]
    data['is_assistant'] = data['isAssistant']
    
    wants = ['fullName', 'coach_name', 'is_assistant']
    return(data[wants].sort_values(by = ['fullName']))

    ### END SOLUTION

## 05. Define a function `create_nba_teams_and_players()` which generates a current player roster dataframe for NBA franchise teams in standard league as expected given `teams.json` and `players.json` in working directory.

- Expected inputs: None
- Expected outputs: `pd.DataFrame`

```
               fullName        player_name
0         Atlanta Hawks  Bogdan Bogdanovic
1         Atlanta Hawks       Clint Capela
2         Atlanta Hawks       John Collins
3         Atlanta Hawks     Sharife Cooper
4         Atlanta Hawks       Gorgui Dieng
..                  ...                ...
501  Washington Wizards      Corey Kispert
502  Washington Wizards         Kyle Kuzma
503  Washington Wizards          Raul Neto
504  Washington Wizards        Isaiah Todd
505  Washington Wizards    Cassius Winston

[506 rows x 2 columns]
```

In [ ]:
def create_nba_teams_and_players() -> pd.DataFrame:
    """
    >>> nba_teams_and_players = create_nba_teams_and_players()
    >>> type(nba_teams_and_players)
    pandas.core.frame.DataFrame
    >>> nba_teams_and_players.shape
    (506, 2)
    """
    ### BEGIN SOLUTION
    
    with open('teams.json', 'r') as file:
        teams = json.load(file)
    file.close()

    standard_teams = []
    for i in teams['league']['vegas']:
        if i["isNBAFranchise"] == True:
            standard_teams.append(i['teamId'])

    def collapse_lists(data):
            result = []
            for d in data:
                entry = {}                      
                if d['teamId'] in standard_teams:
                    for k, v in d.items():
                        entry.update({k: v})
                    result.append(entry)
            return result

    with open('players.json', 'r') as f:
        data = pd.DataFrame(collapse_lists(json.load(f)['league']['standard']))

    std_teams_dict = {}
    for i in teams['league']['vegas']:
        if i["isNBAFranchise"] == True:
            std_teams_dict.update({i["teamId"]: i["fullName"]})

    std_teams = []
    for i in data['teamId']:
        std_teams.append(std_teams_dict[i])

    data['fullName'] = pd.DataFrame(std_teams)
    data["player_name"] = data["firstName"] + ' ' + data["lastName"]
    wants = ['fullName', "player_name"]
    return(data[wants].sort_values(by = ['fullName','player_name']).reset_index(drop = True))

    ### END SOLUTION

## 06. Define a function `find_nba_head_coaches()` which finds out the current head coach of each NBA franchise team in standard league as expected given `teams.json` and `coaches.json` in working directory.

- Expected inputs: None
- Expected outputs: `pd.DataFrame`

```
                  fullName              coach_name  is_assistant
0            Atlanta Hawks           Nate McMillan         False
1           Boston Celtics               Ime Udoka         False
2            Brooklyn Nets              Steve Nash         False
3        Charlotte Hornets           James Borrego         False
4            Chicago Bulls           Billy Donovan         False
5      Cleveland Cavaliers  John-Blair Bickerstaff         False
6         Dallas Mavericks              Jason Kidd         False
7           Denver Nuggets          Michael Malone         False
8          Detroit Pistons             Dwane Casey         False
9    Golden State Warriors              Steve Kerr         False
10         Houston Rockets           Stephen Silas         False
11          Indiana Pacers           Rick Carlisle         False
12             LA Clippers              Tyronn Lue         False
13      Los Angeles Lakers             Frank Vogel         False
14       Memphis Grizzlies          Taylor Jenkins         False
15              Miami Heat          Erik Spoelstra         False
16         Milwaukee Bucks        Mike Budenholzer         False
17  Minnesota Timberwolves             Chris Finch         False
18    New Orleans Pelicans            Willie Green         False
19         New York Knicks           Tom Thibodeau         False
20   Oklahoma City Thunder         Mark Daigneault         False
21           Orlando Magic           Jamahl Mosley         False
22      Philadelphia 76ers              Doc Rivers         False
23            Phoenix Suns          Monty Williams         False
24  Portland Trail Blazers        Chauncey Billups         False
25        Sacramento Kings            Alvin Gentry         False
26       San Antonio Spurs          Gregg Popovich         False
27         Toronto Raptors              Nick Nurse         False
28               Utah Jazz             Quin Snyder         False
29      Washington Wizards          Wes Unseld Jr.         False
```

In [ ]:
def find_nba_head_coaches() -> pd.DataFrame:
    """
    >>> nba_head_coaches = find_nba_head_coaches()
    >>> type(nba_head_coaches)
    pandas.core.frame.DataFrame
    >>> nba_head_coaches.shape
    (30, 3)
    """
    ### BEGIN SOLUTION
    
    with open('coaches.json', 'r') as f:
        data = json.load(f)["league"]["standard"]

    tri = []
    for i in data:
        tri.append(i["teamSitesOnly"]["teamTricode"])
        
    with open('teams.json', 'r') as file:
        teams = json.load(file)
    file.close()

    standard_teams = {}
    for i in teams['league']['vegas']:
        if i["isNBAFranchise"] == True:
            standard_teams.update({i["tricode"]: i["fullName"]})

    data = pd.DataFrame(data)

    str_teams = []
    for i in tri:
        str_teams.append(standard_teams[i])

    data['fullName'] = pd.DataFrame(str_teams)   
    data["coach_name"] = data["firstName"] + ' ' + data["lastName"]
    data['is_assistant'] = data['isAssistant']
    wants = ['fullName', 'coach_name', 'is_assistant']


    filter = (data['isAssistant'] == False)
    return(data[wants][filter].sort_values(by = ['fullName']).reset_index(drop = True))

    ### END SOLUTION

## 07. Define a function `find_bkn_phx_rosters()` which finds out the current coach and player roster of NBA franchise team in standard league: the Brooklyn Nets and the Phoenix Suns as expected given `teams.json`, `coaches.json`, and `players.json` in working directory.

- Expected inputs: None
- Expected outputs: `pd.DataFrame`

```
         fullName                name             type
0   Brooklyn Nets     Adam Harrington  Assistant coach
1   Brooklyn Nets       Blake Griffin           Player
2   Brooklyn Nets         Brian Keefe  Assistant coach
3   Brooklyn Nets         Bruce Brown           Player
4   Brooklyn Nets          Cam Thomas           Player
5   Brooklyn Nets      David Duke Jr.           Player
6   Brooklyn Nets    David Vanterpool  Assistant coach
7   Brooklyn Nets      Day'Ron Sharpe           Player
8   Brooklyn Nets     DeAndre' Bembry           Player
9   Brooklyn Nets       Jacque Vaughn  Assistant coach
10  Brooklyn Nets        James Harden           Player
11  Brooklyn Nets       James Johnson           Player
12  Brooklyn Nets        Jevon Carter           Player
13  Brooklyn Nets          Joe Harris           Player
14  Brooklyn Nets          Jordan Ott  Assistant coach
15  Brooklyn Nets     Kessler Edwards           Player
16  Brooklyn Nets        Kevin Durant           Player
17  Brooklyn Nets        Kyrie Irving           Player
18  Brooklyn Nets   LaMarcus Aldridge           Player
19  Brooklyn Nets         Nic Claxton           Player
20  Brooklyn Nets         Patty Mills           Player
21  Brooklyn Nets        Paul Millsap           Player
22  Brooklyn Nets          Royal Ivey  Assistant coach
23  Brooklyn Nets  Ryan Forehan-Kelly  Assistant coach
24  Brooklyn Nets   Sebastien Poirier  Assistant coach
25  Brooklyn Nets          Steve Nash       Head coach
26  Brooklyn Nets      Tiago Splitter  Assistant coach
27   Phoenix Suns         Abdel Nader           Player
28   Phoenix Suns        Brian Randle  Assistant coach
29   Phoenix Suns         Bryan Gates  Assistant coach
30   Phoenix Suns     Cameron Johnson           Player
31   Phoenix Suns       Cameron Payne           Player
32   Phoenix Suns  Chandler Hutchison           Player
33   Phoenix Suns          Chris Paul           Player
34   Phoenix Suns         Dario Saric           Player
35   Phoenix Suns       Deandre Ayton           Player
36   Phoenix Suns        Devin Booker           Player
37   Phoenix Suns       Elfrid Payton           Player
38   Phoenix Suns      Frank Kaminsky           Player
39   Phoenix Suns       Ish Wainright           Player
40   Phoenix Suns        JaVale McGee           Player
41   Phoenix Suns         Jae Crowder           Player
42   Phoenix Suns         Jalen Smith           Player
43   Phoenix Suns        Jarrett Jack  Assistant coach
44   Phoenix Suns         Kevin Young  Assistant coach
45   Phoenix Suns       Landry Shamet           Player
46   Phoenix Suns         Mark Bryant  Assistant coach
47   Phoenix Suns      Michael Ruffin  Assistant coach
48   Phoenix Suns       Mikal Bridges           Player
49   Phoenix Suns      Monty Williams       Head coach
50   Phoenix Suns         Randy Ayers  Assistant coach
51   Phoenix Suns        Steve Scalzi  Assistant coach
```

In [ ]:
def find_bkn_phx_rosters() -> pd.DataFrame:
    """
    >>> bkn_phx_rosters = find_bkn_phx_rosters()
    >>> type(bkn_phx_rosters)
    pandas.core.frame.DataFrame
    >>> bkn_phx_rosters.shape
    (52, 3)
    """
    ### BEGIN SOLUTION
    
    with open('coaches.json', 'r') as f1:
        data1 = json.load(f1)["league"]["standard"]

    with open('players.json', 'r') as f2:
        data2 = json.load(f2)["league"]["standard"]

    def collapse_lists(data):
        result = []
        for d in data:
            entry = {}
            if d['isNBAFranchise'] == True:
                for k, v in d.items():
                    entry.update({k: v})
                result.append(entry)
        return result

    with open('teams.json', 'r') as f3:
        data3 = pd.DataFrame(collapse_lists(json.load(f3)['league']['vegas']))

    def find_team_members(team_tri):
        team_dict = {}
        for i in data1:
            if i["teamSitesOnly"]["teamTricode"] == team_tri:
                coach_name =  i["firstName"] + ' ' + i["lastName"]
                if i['isAssistant'] == False:
                    team_dict.update({coach_name: 'Head coach'})
                else:
                    team_dict.update({coach_name: 'Assistant coach'})

        filter = (data3['tricode'] == team_tri)
        team_id = data3[filter]['teamId'].iloc[0]

        for i in data2:
            if i['teamId'] == str(team_id):
                player_name = i["firstName"] + ' ' + i["lastName"]
                team_dict.update({player_name: 'player'})
        ans1 = pd.DataFrame(list(team_dict.items()), columns = ['name', 'type'])
        return(ans1)
    ans1 = find_team_members('BKN')
    ans1['fullName'] = 'Brooklyn Nets'
    ans2 = find_team_members('PHX')
    ans2['fullName'] = 'Phoenix Suns'
    wants = ['fullName', 'name', 'type']

    ans = pd.concat([ans1[wants], ans2[wants]]).sort_values(by = ['fullName', 'name']).reset_index(drop = True)
    return ans
    
    ### END SOLUTION

## 08. Define a function named `summarize_pandemic_by_country()` which generates a dataframe to summarize the pandemic globally as of 2021-12-06 given `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` in working directory.

- Expected inputs: None.
- Expected outputs: `pd.DataFrame`

```
         Country/Region  Confirmed   Deaths
0           Afghanistan   44075469  1891966
1               Albania   49688753   880479
2               Algeria   62387154  1786906
3               Andorra    5245208    56731
4                Angola   14418984   361912
..                  ...        ...      ...
191             Vietnam   97392343  2202942
192  West Bank and Gaza  113074593  1204385
193               Yemen    2533958   540481
194              Zambia   49471134   810796
195            Zimbabwe   26746050   945766

[196 rows x 3 columns]
```

In [ ]:
def summarize_pandemic_by_country() -> pd.DataFrame:
    """
    >>> pandemic_by_country = summarize_pandemic_by_country()
    >>> type(pandemic_by_country)
    pandas.core.frame.DataFrame
    >>> pandemic_by_country.shape
    (196, 3)
    """
    ### BEGIN SOLUTION
    
    df1 = pd.read_csv('time_series_covid19_confirmed_global.csv')
    df2 = pd.read_csv('time_series_covid19_deaths_global.csv')
    
    def trans_df(df):
        df = df.drop(['Lat', 'Long'], axis = 1)
        df_sum = df.sum(axis = 1)
        return df_sum
    
    df1['Confirmed'] = trans_df(df1)
    df1['Deaths'] = trans_df(df2)

    wants1 = ['Country/Region', 'Confirmed', 'Deaths']
    wants2 = ['Confirmed', 'Deaths']
    df_wants = df1[wants1]
    temp = df_wants.groupby('Country/Region').sum()
    index = list(temp.index)

    c_r = pd.DataFrame(index, columns = ['Country/Region'])
    temp = temp[wants2].reset_index(drop = True)

    ans = pd.concat([c_r, temp], axis = 1)
    return(ans)
    
    ### END SOLUTION

## 09. Define a function named `find_taiwan_from_covid_time_series()` which generates a dataframe of Taiwan's confirmed and deaths cases given `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` in working directory. Remove the asterisk in `Country/Region` column.

- Expected inputs: None.
- Expected outputs: `pd.DataFrame`

```
    Country/Region     Date  Confirmed  Deaths
0           Taiwan  1/22/20          1       0
1           Taiwan  1/23/20          1       0
2           Taiwan  1/24/20          3       0
3           Taiwan  1/25/20          3       0
4           Taiwan  1/26/20          4       0
..             ...      ...        ...     ...
680         Taiwan  12/2/21      16626     848
681         Taiwan  12/3/21      16637     848
682         Taiwan  12/4/21      16648     848
683         Taiwan  12/5/21      16652     848
684         Taiwan  12/6/21      16662     848

[685 rows x 4 columns]
```

In [ ]:
def find_taiwan_from_covid_time_series() -> pd.DataFrame:
    """
    >>> taiwan_from_covid_time_series = find_taiwan_from_covid_time_series()
    >>> type(taiwan_from_covid_time_series)
    pandas.core.frame.DataFrame
    >>> taiwan_from_covid_time_series.shape
    (685, 4)
    """
    ### BEGIN SOLUTION
    
    df1 = pd.read_csv('time_series_covid19_confirmed_global.csv')
    df2 = pd.read_csv('time_series_covid19_deaths_global.csv')

    def replace_asterisk(x):
        if "*" in x:
            return x.replace("*", "")
        else:
            return x

    def trans_df(df):
        df = df.drop(['Province/State', 'Lat', 'Long'], axis = 1)
        df['Country/Region'] = df['Country/Region'].map(replace_asterisk)
        df = df.melt(id_vars=["Country/Region"], var_name="Date")
        df = df.loc[df['Country/Region'] == 'Taiwan']
        return df

    df = trans_df(df1)
    df.rename(columns = {'value': 'Confirmed'}, inplace = True)
    temp = trans_df(df2)
    temp.rename(columns = {'value': 'Deaths'}, inplace = True)

    ans = pd.merge(df, temp)
    return(ans)
    
    ### END SOLUTION

## 10. Define a function named `transform_taiwan_data` that is able to tranform the dataframe obtained from the previous question into a desired time series format given `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` in working directory.

- Expected inputs: None.
- Expected outputs: `pd.DataFrame`

```
           Country/Region   Variable  Value
Date                                       
2020-01-22         Taiwan  Confirmed      1
2020-01-22         Taiwan     Deaths      0
2020-01-23         Taiwan  Confirmed      1
2020-01-23         Taiwan     Deaths      0
2020-01-24         Taiwan  Confirmed      3
...                   ...        ...    ...
2021-12-04         Taiwan     Deaths    848
2021-12-05         Taiwan  Confirmed  16652
2021-12-05         Taiwan     Deaths    848
2021-12-06         Taiwan  Confirmed  16662
2021-12-06         Taiwan     Deaths    848

[1370 rows x 3 columns]
```

In [ ]:
def transform_taiwan_data() -> pd.DataFrame:
    """
    >>> taiwan_data = transform_taiwan_data()
    >>> type(taiwan_data)
    pandas.core.frame.DataFrame
    >>> taiwan_data.shape
    (1370, 3)
    """
    ### BEGIN SOLUTION
    
    df1 = pd.read_csv('time_series_covid19_confirmed_global.csv')
    df2 = pd.read_csv('time_series_covid19_deaths_global.csv')

    def replace_asterisk(x):
        if "*" in x:
            return x.replace("*", "")
        else:
            return x

    def trans_df(df):
        df = df.drop(['Province/State', 'Lat', 'Long'], axis = 1)
        df['Country/Region'] = df['Country/Region'].map(replace_asterisk)
        df = df.melt(id_vars=["Country/Region"], var_name="Date")
        df = df.loc[df['Country/Region'] == 'Taiwan']
        df['Date'] = pd.to_datetime(df['Date'])
        df.rename(columns = {'value': 'Value'}, inplace = True)
        return df

    df = trans_df(df1).reset_index(drop = True)
    temp = trans_df(df2).reset_index(drop = True)

    c_list = df['Value'].tolist()
    d_list = temp['Value'].tolist()
    df['Variable'] = 'Confirmed'
    temp['Variable'] = 'Deaths'

    ans = pd.concat([df, temp])
    ans = ans[['Date', 'Country/Region', 'Variable', 'Value']]
    ans = ans.sort_values(['Date', 'Variable'])
    ans.set_index('Date', inplace = True)
    ans = ans.sort_index(axis = 0)
    return(ans)
    
    ### END SOLUTION